import GameField from '../game-field/GameField';
import styles from './game.module.css'

function game() {
  const fields = [
    { name: 'БЕСПЛАТНАЯ СТОЯНКА' },
    { name: 'УЛ. ТВЕРСКСЯ' },
    { name: 'ШАНС' },
    { name: 'УЛ. ПУШКИНСКАЯ' },
    { name: 'ПЛОЩАДЬ МАЯКОВСКОГО' },
    { name: 'КАЗАНСКАЯ ЖЕЛЕЗНАЯ ДОРОГА' },
    { name: 'УЛ. ГРУЗИНСКИЙ ВАЛ' },
    { name: 'УЛ. ЧАЙКОВСКОГО' },
    { name: 'ВОДОПРОВОД' },
    { name: 'СМОЛЕНСКАЯ ПЛОЩАДЬ' },
    { name: 'ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ' },
    { name: 'БЕСПЛАТНАЯ СТОЯНКА' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: 'ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ' },
    { name: 'БЕСПЛАТНАЯ СТОЯНКА' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: 'ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ' },
    { name: 'БЕСПЛАТНАЯ СТОЯНКА' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: 'ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ' },
    { name: 'БЕСПЛАТНАЯ СТОЯНКА' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: 'ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ' },
    { name: 'БЕСПЛАТНАЯ СТОЯНКА' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: 'ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ' },
    { name: 'БЕСПЛАТНАЯ СТОЯНКА' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: 'ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ' },
    { name: 'БЕСПЛАТНАЯ СТОЯНКА' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: 'ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ' },
    { name: 'БЕСПЛАТНАЯ СТОЯНКА' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: 'ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ' },
    { name: 'БЕСПЛАТНАЯ СТОЯНКА' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: '' },
    { name: 'ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ' },
    { name: 'БЕСПЛАТНАЯ СТОЯНКА' },
    { name: 'УЛ. ТВЕРСКСЯ' },
    { name: 'ШАНС' },
    { name: 'УЛ. ПУШКИНСКАЯ' },
    { name: 'ПЛОЩАДЬ МАЯКОВСКОГО' },
    { name: 'КАЗАНСКАЯ ЖЕЛЕЗНАЯ ДОРОГА' },
    { name: 'УЛ. ГРУЗИНСКИЙ ВАЛ' },
    { name: 'УЛ. ЧАЙКОВСКОГО' },
    { name: 'ВОДОПРОВОД' },
    { name: 'СМОЛЕНСКАЯ ПЛОЩАДЬ' },
    { name: 'ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ' },
  ]

  return (
    <div className={styles.container}>
      <div className={`${styles.section} ${styles.stop}`}>Остановка</div>
      <div className={`${styles.section} ${styles.top_section}`}>Верхняя секция</div>
      <div className={`${styles.section} ${styles.goto_prison}`}>В тюрьму</div>
      <div className={`${styles.section} ${styles.left_section}`}>Левая секция</div>
      <div className={`${styles.section} ${styles.chat_section}`}>Секция чата</div>
      <div className={`${styles.section} ${styles.right_section}`}>Правая секция</div>
      <div className={`${styles.section} ${styles.forward_joly}`}>Посетить тюрьму</div>
      <div className={`${styles.section} ${styles.lower_section}`}>Нижняя секция</div>
      <div className={`${styles.section} ${styles.start}`}>Вперёд</div>
      {/* {fields.map(field => (
        <GameField name={field.name} />
      ))} */}
    </div>
  )
}

export default game;