export enum GamePaymentType {
    BUY_GAME_FIELD = 'BUY_GAME_FIELD',
    PAY_RENT = 'PAY_PROPERTY_RENT',
    PAY_TAX = 'PAY_TAX',
    PAY_ACTION_CARD = 'PAY_ACTION_CARD',
    PAY_PLAYERS = 'PAY_PLAYERS',
    PROPERTY_REPAIR = 'PROPERTY_REPAIR'
}